#!/usr/bin/lua

function dit.onBreakLine()
   if dit.getLastKey() == "{" then
      dit.write("}")
      dit.backwardChar()
      dit.breakIndenting(dit.getIndentSize())
      dit.indent()
   end
end
