FILES
name prefix Makefile
name prefix makefile
name prefix GNUmakefile
RULES

context # `$ dim
   rule $(`[A`-Za`-z`]`+) brightalt
/context

rule : brightdiff

context = `$ brightdiff normal alt
/context

context `s`s`s`s`s`s`s`s `$ veryspecial diff diff
   rule $(`[A`-Za`-z_`]`+) brightalt
   context " " diff
   /context
/context
