FILES
name prefix Makefile
name prefix makefile
name prefix GNUmakefile
RULES
context # `$ dim
   rule $(`[A`-Za`-z`]`+) brightalt
/context
rule : brightdiff
rule `s`s`s`s`s`s`s`s veryspecial
context = `$ alt
/context
rule = brightdiff
rule $(`[A`-Za`-z`]`+) brightalt
